
project_id = "pzlkzzivojcrfooelyky"

[functions.flutterwave-payment]
verify_jwt = true

[functions.paystack-payment]
verify_jwt = true

[functions.verify-flutterwave]
verify_jwt = true

[functions.verify-paystack]
verify_jwt = true
